apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      app: nodejs-nodeapp